### ISSUE TITLE
time.elapsed is a timestamp when idle, but a timespan when running

### ISSUE THREAD

**Issue by gwh-cpnet** [onury/tasktimer#11]
Is it on purpose? 

from my point of view, time.elapsed should be 0 when its state is idle. Anyway, put them into the same variable looks weird.

**Comment by onury** [comment]
No. That's a bug. Good catch actually. 
Thanks.

**Comment by onury** [comment]
Bug demonstration: https://runkit.com/onury/tasktimer-issue-11

**Comment by onury** [comment]
Fixed in v3.0.0

**Comment by gwh-cpnet** [comment]
Thanks for clarifying and quick fix.
