### ISSUE TITLE
recursive callback doubling timer ticks

### ISSUE THREAD

**Issue by igaln** [onury/tasktimer#15]
Trying to use a Callback from a Task to re-create the Tasks, for ex:

`InitializeTasks () {
timer.reset();
timer.add[{
  callback(task) { InitializeTasks() }
}
}`

This causes the Ticks to double. Any ideas how to approach this? Can the callbacks handle additional parameters?

**Comment by onury** [comment]
> This causes the Ticks to double. Any ideas how to approach this?

I'm not sure if I get this. Do you mean number of total ticks double? or each tick is executed twice?

In your callback, you call `.reset()` which also stops the timer. You need to call `.start()` in there to re-run it. And then, this kind of code might run endlessly.. 

> Can the callbacks handle additional parameters?

Only `task` parameter is passed to the callback when it's invoked.
