### ISSUE TITLE
Task startDate ignored?

### ISSUE THREAD

**Issue by adrfantini** [onury/tasktimer#29]
Hi! I am trying to use the `startDate` feature, like this:
```js
const { TaskTimer } = require('tasktimer');
const baseTimerTick = 60 * 1000;
const timer = new TaskTimer(baseTimerTick);
let now = new Date().getTime();
let nextStart = new Date(Math.ceil( now / baseTimerTick) * baseTimerTick );
timer.add({
    id: 'logTime',
    callback: () => console.log(new Date()),
    startDate: nextStart
}).start();
// timer should start at the next minute and 00 seconds!
```
However, this does not seem to work, and the timer starts exactly 1 minute form whenever it was defined. Why?
Thanks in advance!

**Comment by onury** [comment]
Timer interval is the minimum time resolution; meaning, any configured task will execute on multiples of this interval, never in between. For example, when your interval is 1000 ms and if a task is configured to start running on 2500th ms, it will execute on next interval which is 3000. This is done for efficiency and performance.

If you need more resolution, set a lower interval and configure a larger `tickInterval` for your task.
For `startDate`; the task will execute on the first tick, closest to the given start date.

[See demo](https://runkit.com/onury/600c6c515ea79d00192e40d1).

**Comment by adrfantini** [comment]
You are correct! I was mistaken, it is definitely working as intended ;)
Thank you for this awesome little tool!
