### ISSUE TITLE
Task defaults - documentation inconsistency

### ISSUE THREAD

**Issue by bazineta** [onury/tasktimer#5]
While tasks (i.e., the addTask() documentation) are documented as having a couple of default options, this appears to be true only if a string is passed to addTask(). If an object is passed, then the documented defaults do not appear to be applied.

**Comment by onury** [comment]
TaskTimer v2.0.0 is finally released. There are some [breaking changes](https://github.com/onury/tasktimer/blob/master/CHANGELOG.md).
