### ISSUE TITLE
does this library fixes known setTimeout and setInterval inconsistency?

### ISSUE THREAD

**Issue by bboydflo** [onury/tasktimer#6]
Relying on setInterval and setTimeout is not accurate. I have look at the code a little but couldn't figure out if timers issues/inconsistencies are handled.

**Comment by onury** [comment]
Been a long time but TaskTimer v2.0.0 is finally released. With this version, JS timer inaccuracy problem is properly handled. See [this for more](https://onury.io/tasktimer/#features).
