### ISSUE TITLE
totalRuns not working for task

### ISSUE THREAD

**Issue by mk53202** [onury/tasktimer#7]
It looks like totalRuns is not being respected and loop execution continues. Ticks keep incrementing after totalRuns is reached but no new tasks are executed (which I guess is good)

I've added the code below to the callback function example in the documentation as a work around.

```js
    callback: function (task) {
        console.log(task.name + ' task has run ' + task.currentRuns + ' times.');
         if( task.currentRuns >= task.totalRuns ) {
           timer.stop()
         }
    }
```

Any ideas?

**Comment by onury** [comment]
That's right and expected behavior. `totalRuns` is the **task's** configuration, not the **timer's**. You might have added multiple tasks or you could use the `tick` event to run code... Timer needs to be stopped via `.stop()`. For an example:

```js
const timer = new TaskTimer(30000);
timer.addTask({
    name: 'job-1',
    tickInterval: 2,
    totalRuns: 3,
    callback(task) {
        console.log(`This will run every 60 secs. 3 times, but timer will go on...`);
    }
});
timer.addTask({
    name: 'job-2',
    tickInterval: 5,
    totalRuns: 5,
    callback(task) {
        console.log(`This will run every 150 secs. 5 times, but timer will go on...`);
    }
});
timer.on('tick', () => {
    console.log('This runs every 30 sec. until .stop() is called.');
});
timer.start();
```

**Comment by onury** [comment]
By the way, I will add the following features soon:

- `delay` (task config): initial delay in milliseconds before running the task for the first time.
- `COMPLETE` (event): fires when all tasks are complete.
- `stopOnComplete` (timer config): auto-stops the timer when all tasks are complete.

.. and some more. The last two would be convenient for you I think.

**Comment by mk53202** [comment]
That makes send. I misread the doc of course. Thank again for your
wonderful contribution. Great utility!

Mk...

**Comment by onury** [comment]
Thanks. You're welcome!
